// Generated by Claude
const express = require('express');
const { MongoClient } = require('mongodb');
const bodyParser = require('body-parser');

const app = express();
const PORT = 3000;
const MONGO_URL = 'mongodb://localhost:27017';
const DB_NAME = 'nosql_injection_lab';

app.use(bodyParser.json());
app.use(bodyParser.urlencoded({ extended: true }));

let db;

async function initDatabase() {
    try {
        const client = await MongoClient.connect(MONGO_URL, { 
            useNewUrlParser: true, 
            useUnifiedTopology: true 
        });
        
        db = client.db(DB_NAME);
        console.log('✓ Connected to MongoDB');
        
        await db.collection('products').deleteMany({});
        await db.collection('users').deleteMany({});
        
        await db.collection('products').insertMany([
            { category: 'fizzy', name: 'Cola', price: 2.50, released: 1 },
            { category: 'fizzy', name: 'Lemonade', price: 2.00, released: 1 },
            { category: 'fizzy', name: 'Secret Fizz X', price: 5.00, released: 0 },
            { category: 'juice', name: 'Orange Juice', price: 3.00, released: 1 },
            { category: 'water', name: 'Spring Water', price: 1.50, released: 1 },
            { category: 'tea', name: 'Green Tea', price: 13.37, released: 0 }
        ]);
        
        await db.collection('users').insertMany([
            { username: 'admin', password: 'adminPassword123', role: 'administrator' },
            { username: 'user1', password: 'user123', role: 'user' },
            { username: 'user2', password: 'user234', role: 'user' }
        ]);
        
        console.log('✓ Database seeded with test data');
        
    } catch (error) {
        console.error('✗ MongoDB connection error:', error.message);
        console.error('\nMake sure MongoDB is running:');
        console.error('  mongod --dbpath /path/to/data');
        process.exit(1);
    }
}

app.get('/api/products', async (req, res) => {
    try {
        const category = req.query.category || '';
        
        const whereClause = `this.category == '${category}' && this.released == 1`;
        
        console.log('\n[PRODUCT LOOKUP]');
        console.log('Input:', category);
        console.log('$where clause:', whereClause);
        
        const results = await db.collection('products').find({
            $where: whereClause
        }).toArray();
        
        res.json({
            vulnerable: true,
            query: { $where: whereClause },
            results: results,
            count: results.length
        });
        
    } catch (error) {
        console.error('Query error:', error.message);
        res.status(400).json({
            error: error.message,
            query: req.query
        });
    }
});

app.post('/api/login', async (req, res) => {
    try {
        const { username, password } = req.body;
        
        console.log('\n[LOGIN ATTEMPT]');
        console.log('Username:', username);
        console.log('Password:', password);
        
        const query = {
            username: username,
            password: password
        };
        
        console.log('Query:', JSON.stringify(query, null, 2));
        
        const user = await db.collection('users').findOne(query);
        
        if (user) {
            res.json({
                success: true,
                message: `Logged in as ${user.username}`,
                user: user,
                query: query
            });
        } else {
            res.json({
                success: false,
                message: 'Invalid credentials',
                query: query
            });
        }
        
    } catch (error) {
        console.error('Login error:', error.message);
        res.status(400).json({
            error: error.message,
            query: req.body
        });
    }
});

app.get('/api/user', async (req, res) => {
    try {
        const username = req.query.username || '';
        
        const whereClause = `this.username == '${username}'`;
        
        console.log('\n[USER LOOKUP]');
        console.log('Input:', username);
        console.log('$where clause:', whereClause);
        
        const results = await db.collection('users').find({
            $where: whereClause
        }).toArray();
        
        const sanitized = results.map(u => ({ ...u, password: '***' }));
        
        res.json({
            vulnerable: true,
            query: { $where: whereClause },
            results: sanitized,
            actualResults: results, 
            count: results.length
        });
        
    } catch (error) {
        console.error('Query error:', error.message);
        res.status(400).json({
            error: error.message,
            query: req.query
        });
    }
});

app.post('/api/query', async (req, res) => {
    try {
        const query = req.body;
        
        console.log('\n[CUSTOM QUERY]');
        console.log('Query:', JSON.stringify(query, null, 2));
        
        const results = await db.collection('users').find(query).toArray();
        
        const sanitized = results.map(u => ({ ...u, password: '***' }));
        
        res.json({
            vulnerable: true,
            query: query,
            results: sanitized,
            actualResults: results,
            count: results.length
        });
        
    } catch (error) {
        console.error('Query error:', error.message);
        res.status(400).json({
            error: error.message,
            query: req.body
        });
    }
});

app.get('/', (req, res) => {
    res.send(`
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NoSQL Injection Lab</title>
    <style>
        * { margin: 0; padding: 0; box-sizing: border-box; }
        body {
            font-family: 'Consolas', 'Monaco', monospace;
            background: #0d1117;
            color: #58a6ff;
            padding: 20px;
            line-height: 1.6;
        }
        .container { max-width: 1400px; margin: 0 auto; }
        h1 { color: #58a6ff; margin-bottom: 10px; font-size: 28px; text-align: center; }
        .info { color: #8b949e; margin-bottom: 30px; text-align: center; }
        .db-view {
            background: #161b22;
            border: 1px solid #30363d;
            padding: 20px;
            margin-bottom: 30px;
            border-radius: 6px;
        }
        .db-view h2 { color: #58a6ff; font-size: 18px; margin-bottom: 15px; }
        .db-view pre {
            background: #0d1117;
            padding: 15px;
            border-radius: 6px;
            overflow-x: auto;
            color: #c9d1d9;
            font-size: 13px;
        }
        .test-section {
            background: #161b22;
            border: 1px solid #30363d;
            padding: 25px;
            margin-bottom: 25px;
            border-radius: 6px;
        }
        .test-section h2 {
            color: #58a6ff;
            font-size: 20px;
            margin-bottom: 20px;
            border-bottom: 1px solid #30363d;
            padding-bottom: 10px;
        }
        .input-group { margin-bottom: 20px; }
        label {
            display: block;
            margin-bottom: 8px;
            color: #8b949e;
            font-size: 14px;
        }
        input[type="text"], textarea {
            width: 100%;
            padding: 12px;
            background: #0d1117;
            border: 1px solid #30363d;
            color: #c9d1d9;
            font-family: 'Consolas', 'Monaco', monospace;
            font-size: 14px;
            border-radius: 6px;
        }
        input[type="text"]:focus, textarea:focus {
            outline: none;
            border-color: #58a6ff;
        }
        textarea { resize: vertical; min-height: 100px; }
        button {
            background: #238636;
            color: #ffffff;
            border: none;
            padding: 12px 24px;
            font-family: 'Consolas', 'Monaco', monospace;
            font-weight: bold;
            cursor: pointer;
            font-size: 14px;
            border-radius: 6px;
            margin-top: 10px;
            transition: background 0.2s;
        }
        button:hover { background: #2ea043; }
        .output-box {
            margin-top: 20px;
            padding: 20px;
            background: #0d1117;
            border: 1px solid #30363d;
            border-radius: 6px;
            min-height: 150px;
        }
        .output-box h3 { color: #58a6ff; font-size: 16px; margin-bottom: 12px; }
        .query-display {
            background: #161b22;
            padding: 12px;
            border-left: 3px solid #f85149;
            margin: 10px 0;
            font-family: 'Consolas', 'Monaco', monospace;
            color: #ff7b72;
            word-wrap: break-word;
        }
        .result-display {
            background: #161b22;
            padding: 15px;
            border-left: 3px solid #3fb950;
            margin: 10px 0;
        }
        .result-display pre { color: #a5d6ff; margin: 0; overflow-x: auto; }
        .error {
            color: #f85149;
            padding: 10px;
            background: rgba(248, 81, 73, 0.1);
            border-radius: 6px;
            margin: 10px 0;
        }
        .success {
            color: #3fb950;
            padding: 10px;
            background: rgba(63, 185, 80, 0.1);
            border-radius: 6px;
            margin: 10px 0;
        }
        .hint {
            background: #1f6feb;
            color: #ffffff;
            padding: 8px 12px;
            border-radius: 6px;
            font-size: 12px;
            display: inline-block;
            margin: 5px 5px 5px 0;
            cursor: pointer;
        }
        .hint:hover { background: #388bfd; }
        .mongodb-badge {
            display: inline-block;
            background: #13aa52;
            color: white;
            padding: 4px 8px;
            border-radius: 4px;
            font-size: 11px;
            font-weight: bold;
            margin-left: 10px;
        }
    </style>
</head>
<body>
    <div class="container">
        <h1>NoSQL Injection Lab</h1>

        <div class="db-view">
            <h2>📊 MongoDB Collections</h2>
            <pre>db.products.find()
[
  { category: "fizzy", name: "Cola", price: 2.50, released: 1 },
  { category: "fizzy", name: "Lemonade", price: 2.00, released: 1 },
  { category: "fizzy", name: "Secret Fizz X", price: 5.00, released: 0 },
  { category: "juice", name: "Orange Juice", price: 3.00, released: 1 },
  { category: "water", name: "Spring Water", price: 1.50, released: 1 }
]

db.users.find()
[
  { username: "admin", password: "admin123", role: "administrator" },
  { username: "wiener", password: "peter", role: "user" },
  { username: "carlos", password: "montoya", role: "user" }
]</pre>
        </div>

        <!-- Test 1: Product Search -->
        <div class="test-section">
            <h2>🔍 Test 1: Product Search ($where Syntax Injection)</h2>
            <p style="color: #8b949e; margin-bottom: 15px;">
                Backend Query: <code style="color: #a5d6ff;">db.products.find({ $where: "this.category == '\${input}' && this.released == 1" })</code>
            </p>
            
            <div class="input-group">
                <label>Category parameter:</label>
                <input type="text" id="input1" placeholder="fizzy">
            </div>
            
            <div>
                <div class="hint" onclick="setInput('input1', 'fizzy')">Normal: fizzy</div>
                <div class="hint" onclick="setInput('input1', \`fizzy' || '1'=='1\`)">Break out: fizzy' || '1'=='1</div>
                <div class="hint" onclick="setInput('input1', \`fizzy' || 1==1 || 'a'=='a\`)">Always true: fizzy' || 1==1 || 'a'=='a</div>
                <div class="hint" onclick="setInput('input1', \`fizzy' || this.released==0 || 'a'=='b\`)">Show unreleased: fizzy' || this.released==0 || 'a'=='b</div>
            </div>
            
            <button onclick="test1()">Execute MongoDB Query</button>
            <div class="output-box" id="output1"></div>
        </div>

        <!-- Test 2: Login -->
        <div class="test-section">
            <h2>🔐 Test 2: Login (Operator Injection)</h2>
            <p style="color: #8b949e; margin-bottom: 15px;">
                Backend Query: <code style="color: #a5d6ff;">db.users.findOne({ username: input1, password: input2 })</code>
            </p>
            
            <div class="input-group">
                <label>Username (accepts JSON operators):</label>
                <textarea id="input2a">wiener</textarea>
            </div>
            
            <div class="input-group">
                <label>Password (accepts JSON operators):</label>
                <textarea id="input2b">peter</textarea>
            </div>
            
            <div>
                <div class="hint" onclick="setInput('input2a', 'wiener'); setInput('input2b', 'peter')">Normal: wiener/peter</div>
                <div class="hint" onclick="setInput('input2a', '{&quot;$ne&quot;: &quot;&quot;}'); setInput('input2b', '{&quot;$ne&quot;: &quot;&quot;}')">$ne bypass: {"$ne": ""}</div>
                <div class="hint" onclick="setInput('input2a', '{&quot;$in&quot;: [&quot;admin&quot;, &quot;carlos&quot;]}'); setInput('input2b', '{&quot;$regex&quot;: &quot;^.*&quot;}')">$in + $regex</div>
                <div class="hint" onclick="setInput('input2a', 'admin'); setInput('input2b', '{&quot;$regex&quot;: &quot;^a&quot;}')">Extract password: {"$regex": "^a"}</div>
            </div>
            
            <button onclick="test2()">Attempt Login</button>
            <div class="output-box" id="output2"></div>
        </div>

        <!-- Test 3: User Lookup -->
        <div class="test-section">
            <h2>👤 Test 3: User Lookup ($where JavaScript Injection)</h2>
            <p style="color: #8b949e; margin-bottom: 15px;">
                Backend Query: <code style="color: #a5d6ff;">db.users.find({ $where: "this.username == '\${input}'" })</code>
            </p>
            
            <div class="input-group">
                <label>Username parameter:</label>
                <input type="text" id="input3" placeholder="admin">
            </div>
            
            <div>
                <div class="hint" onclick="setInput('input3', 'admin')">Normal: admin</div>
                <div class="hint" onclick="setInput('input3', \`admin' && this.password[0] == 'a\`)">1st char: admin' && this.password[0] == 'a</div>
                <div class="hint" onclick="setInput('input3', \`admin' && this.password.substring(0,5) == 'admin\`)">Extract: admin' && this.password.substring(0,5) == 'admin</div>
                <div class="hint" onclick="setInput('input3', \`admin' && this.password.match(/^admin/)\`)">Regex: admin' && this.password.match(/^admin/)</div>
            </div>
            
            <button onclick="test3()">Execute MongoDB Query</button>
            <div class="output-box" id="output3"></div>
        </div>

        <!-- Test 4: Advanced -->
        <div class="test-section">
            <h2>⚙️ Test 4: Advanced Query (Full Operator Injection)</h2>
            <p style="color: #8b949e; margin-bottom: 15px;">
                Backend Query: <code style="color: #a5d6ff;">db.users.find(inputJSON)</code>
            </p>
            
            <div class="input-group">
                <label>MongoDB Query (JSON):</label>
                <textarea id="input4" rows="8">{
  "username": "admin"
}</textarea>
            </div>
            
            <div>
                <div class="hint" onclick="setInput('input4', '{\\n  &quot;username&quot;: &quot;admin&quot;\\n}')">Normal query</div>
                <div class="hint" onclick="setInput('input4', '{\\n  &quot;username&quot;: {&quot;$ne&quot;: &quot;&quot;},\\n  &quot;password&quot;: {&quot;$ne&quot;: &quot;&quot;}\\n}')">Get all users</div>
                <div class="hint" onclick="setInput('input4', '{\\n  &quot;username&quot;: &quot;admin&quot;,\\n  &quot;password&quot;: {&quot;$regex&quot;: &quot;^admin1&quot;}\\n}')">Password extraction</div>
                <div class="hint" onclick="setInput('input4', '{\\n  &quot;role&quot;: &quot;administrator&quot;\\n}')">Find admins</div>
            </div>
            
            <button onclick="test4()">Execute MongoDB Query</button>
            <div class="output-box" id="output4"></div>
        </div>
    </div>

    <script>
        function setInput(id, value) {
            document.getElementById(id).value = value;
        }

        function escapeHtml(str) {
            const div = document.createElement('div');
            div.textContent = str;
            return div.innerHTML;
        }

        async function test1() {
            const input = document.getElementById('input1').value;
            const output = document.getElementById('output1');
            
            output.innerHTML = '<div style="color: #8b949e;">Executing MongoDB query...</div>';
            
            try {
                const response = await fetch('/api/products?category=' + encodeURIComponent(input));
                const data = await response.json();
                
                let html = '<h3>MongoDB Query:</h3>';
                html += '<div class="query-display">' + escapeHtml(JSON.stringify(data.query, null, 2)) + '</div>';
                
                if (data.error) {
                    html += '<div class="error">Error: ' + escapeHtml(data.error) + '</div>';
                } else {
                    html += '<div class="success">Found ' + data.count + ' product(s)</div>';
                    html += '<div class="result-display"><pre>' + JSON.stringify(data.results, null, 2) + '</pre></div>';
                }
                
                output.innerHTML = html;
            } catch (error) {
                output.innerHTML = '<div class="error">Request failed: ' + error.message + '</div>';
            }
        }

        async function test2() {
            const usernameInput = document.getElementById('input2a').value.trim();
            const passwordInput = document.getElementById('input2b').value.trim();
            const output = document.getElementById('output2');
            
            output.innerHTML = '<div style="color: #8b949e;">Executing MongoDB query...</div>';
            
            let username, password;
            
            try {
                username = usernameInput.startsWith('{') ? JSON.parse(usernameInput) : usernameInput;
                password = passwordInput.startsWith('{') ? JSON.parse(passwordInput) : passwordInput;
            } catch (e) {
                output.innerHTML = '<div class="error">JSON Parse Error: ' + e.message + '</div>';
                return;
            }
            
            try {
                const response = await fetch('/api/login', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ username, password })
                });
                
                const data = await response.json();
                
                let html = '<h3>MongoDB Query:</h3>';
                html += '<div class="query-display">db.users.findOne(' + JSON.stringify(data.query, null, 2) + ')</div>';
                
                if (data.success) {
                    html += '<div class="success">✓ ' + data.message + '</div>';
                    html += '<div class="result-display"><pre>' + JSON.stringify(data.user, null, 2) + '</pre></div>';
                } else {
                    html += '<div class="error">✗ ' + data.message + '</div>';
                }
                
                output.innerHTML = html;
            } catch (error) {
                output.innerHTML = '<div class="error">Request failed: ' + error.message + '</div>';
            }
        }

        async function test3() {
            const input = document.getElementById('input3').value;
            const output = document.getElementById('output3');
            
            output.innerHTML = '<div style="color: #8b949e;">Executing MongoDB query...</div>';
            
            try {
                const response = await fetch('/api/user?username=' + encodeURIComponent(input));
                const data = await response.json();
                
                let html = '<h3>MongoDB Query:</h3>';
                html += '<div class="query-display">' + escapeHtml(JSON.stringify(data.query, null, 2)) + '</div>';
                
                if (data.error) {
                    html += '<div class="error">Error: ' + escapeHtml(data.error) + '</div>';
                } else {
                    html += '<div class="success">Found ' + data.count + ' user(s)</div>';
                    html += '<h3>Results (passwords hidden):</h3>';
                    html += '<div class="result-display"><pre>' + JSON.stringify(data.results, null, 2) + '</pre></div>';
                    
                    if (data.actualResults && data.actualResults.length > 0) {
                        html += '<h3>Full Results (with passwords):</h3>';
                        html += '<div class="result-display"><pre>' + JSON.stringify(data.actualResults, null, 2) + '</pre></div>';
                    }
                }
                
                output.innerHTML = html;
            } catch (error) {
                output.innerHTML = '<div class="error">Request failed: ' + error.message + '</div>';
            }
        }

        async function test4() {
            const input = document.getElementById('input4').value;
            const output = document.getElementById('output4');
            
            output.innerHTML = '<div style="color: #8b949e;">Executing MongoDB query...</div>';
            
            try {
                const query = JSON.parse(input);
                
                const response = await fetch('/api/query', {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify(query)
                });
                
                const data = await response.json();
                
                let html = '<h3>MongoDB Query:</h3>';
                html += '<div class="query-display">db.users.find(' + JSON.stringify(data.query, null, 2) + ')</div>';
                
                if (data.error) {
                    html += '<div class="error">Error: ' + escapeHtml(data.error) + '</div>';
                } else {
                    html += '<div class="success">Found ' + data.count + ' user(s)</div>';
                    html += '<h3>Results (passwords hidden):</h3>';
                    html += '<div class="result-display"><pre>' + JSON.stringify(data.results, null, 2) + '</pre></div>';
                    
                    if (data.actualResults && data.actualResults.length > 0) {
                        html += '<h3>Full Results (with passwords):</h3>';
                        html += '<div class="result-display"><pre>' + JSON.stringify(data.actualResults, null, 2) + '</pre></div>';
                    }
                }
                
                output.innerHTML = html;
            } catch (error) {
                output.innerHTML = '<div class="error">Error: ' + error.message + '</div>';
            }
        }
    </script>
</body>
</html>
    `);
});

initDatabase().then(() => {
    app.listen(PORT, () => {
        console.log(`\n✓ NoSQL Injection Lab running on http://localhost:${PORT}`);
        console.log('✓ Using real MongoDB database');
        console.log('\nPress Ctrl+C to stop\n');
    });
});
